### ISSUE TITLE
How do I invoke grpc services that need authorization?

### ISSUE THREAD

**Issue by duzhenxun** [fullstorydev/grpcurl#113]
go client code
auth := Authentication{
		appKey:    "duzhenxun",
		appSecret: "password",
	}
	conn, err := grpc.Dial(*addr, grpc.WithInsecure(), grpc.WithPerRPCCredentials(&auth),grpc.WithAuthority("service1"))

Now I want to use curl to request how to add these parameters?
grpcurl -plaintext -authority service1 -d '{"name":"duzhenxun"}'   ???????    127.0.0.1:9080 hello.HelloService.Fun1

**Comment by jhump** [comment]
With `grpcurl`, you have to compute the per-request credential first and then you can supply it as an argument via a `-H` parameter.

So you could have a separate program like so:
```go
auth := Authentication{
    appKey: "duzhenxun",
    appSecret: "password",
}
md, err := auth.GetRequestMetadata(context.Background(), "http://127.0.0.1:9080/hello.HelloService")
if err != nil {
    fmt.Fprintf(os.Stderr, "Failed to compute metadata: %v\n", err)
    os.Exit(1)
}
for k, vals := range md {
    for _, v := range vals {
        fmt.Printf("%s: %s\n", k, v)
    }
}
```
The output of the above program would be the headers you need to pass with the RPC for it to be correctly auth'ed by the server.

**Comment by duzhenxun** [comment]
I see. Thank you very much.

**Comment by jammerful** [comment]
@jhump I'm trying to use grpcurl with my application that uses OIDC tokens for authentication. Would I also expect passing in the token via the header flag to work as well?

`gprcurl -H 'authorization: Bearer <jwt_token>' grpc.server.com:443 my.custom.server.Service/Method`

**Comment by jammerful** [comment]
I figured out what the issue was, the authority psuedo-header contained the port which caused my service mesh not to be able to assign a route to the traffic, overriding the authority fixed the issue. So yes passing in the OIDC token via the header works as expected.
