### ISSUE TITLE
Does grpcurl support ALPN?

### ISSUE THREAD

**Issue by gold-kou** [fullstorydev/grpcurl#125]
As I can see, grpcurl doesn't seem to support ALPN.
Because I could use grpcurl with insecure or no option under NLB(AWS) which doesn't support ALPN.

However couldn't find any docs.

I'm not in trouble now, but i just want to know it.

Thank you.

**Comment by jhump** [comment]
@gold-kou, definitely supports ALPN -- that is how gRPC clients negotiate HTTP/2 as the wire protocol (vs. HTTP 1.1 or SPDY, for example).

I think what you observed is technically a _bug_ in the Go gRPC implementation, that allows the handshake to succeed even if the server does not support ALPN: https://github.com/grpc/grpc-go/issues/2742

**Comment by gold-kou** [comment]
@jhump 
Exactly, I use grpc-go.

According to the link, the communication between grpcurl and the grpc-go server uses HTTP/1 instead of ALPN, because the server doesn't support ALPN.
Right?

**Comment by jhump** [comment]
It is definitely _not_ using HTTP 1.1. Grpcurl uses the grpc-go implementation, which simply does not support HTTP 1.1 (you must use grpc-web for that). What it means is that it is using HTTP/2 even though the protocol was not correctly negotiated.

I am willing to bet that your AWS load balancer is a layer-4/TCP balancer. So it doesn't actually care about the protocol (whether it is HTTP 1.1 or HTTP/2), and your gRPC Go server _does_ speak HTTP/2, so everything is happy, even though no correct protocol was negotiated during the TLS handshake.

**Comment by gold-kou** [comment]
@jhump 
> it doesn't actually care about the protocol (whether it is HTTP 1.1 or HTTP/2), and your gRPC Go server does speak HTTP/2, so everything is happy

You are right.
I just wanted to know detail.

Probably I understand.
ALPN doesn't success completely between grpcurl and the grpc-go server, because the server doesn't support ALPN even though grpcurl tries.
However, it's possible to speak HTTP/2 over TLS, as grpc-go allows TLS handshake. 

Thank you!
