### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by fadc80** [fullstorydev/grpcurl#126]
I installed `grpcurl` from source code, then I tryed:

```shell
grpcurl -v -d '{ "data": { "type": "Buffer", "data": [ 72, 101, 108, 108, 111 ] } }' \ 
  server.mydomain.com.br:5051 pb.Pdf.Validate
```

I got the following error:

> Failed to dial target host "server.mydomain.com.br:5051": tls: first record does not look like a TLS handshake

My server use pure http...

What is my mistake?

Thanks!

**Comment by jhump** [comment]
@fadc80, you want `-plaintext`, not `-insecure`. From the help message (`grpcurl -h`):

```
  -insecure
    	Skip server certificate and domain verification. (NOT SECURE!) Not
    	valid with -plaintext option.
  -plaintext
    	Use plain-text HTTP/2 when connecting to server (no TLS).
```

So `-insecure` means to use TLS, but in an insecure way, skipping the server certificate verification step. The error message clearly indicates that the server is not using TLS, so `-plaintext` is the option you want.
