### ISSUE TITLE
TLS handshake attempted, even with -insecure flag specified.

### ISSUE THREAD

**Issue by arberx** [fullstorydev/grpcurl#128]
On OSX, `grpcurl` (installed with brew) still performs a TLS handshake even when the `-insecure` flag is specified. Below is a simple list command from `grpcurl` compared to `grpc_cli` where the connection succeeds:

```
λ → grpcurl -version                         
grpcurl 1.4.0

λ → grpcurl -v -insecure localhost:50051 list
Failed to dial target host "localhost:50051": tls: first record does not look like a TLS handshake

λ → ./grpc_cli list localhost:50051      
build.bazel.remote.execution.v2.ActionCache
build.bazel.remote.execution.v2.ContentAddressableStorage
build.bazel.remote.execution.v2.Execution
google.longrunning.Operations
grpc.reflection.v1alpha.ServerReflection
```

I apologize if I'm missing something obvious. 

Thanks!

**Comment by jhump** [comment]
@arberx: the `-insecure` flag mode still uses TLS, but turns off server certificate verification. What you want is the `-plaintext` flag. Do `grpcurl -h` to see a list of all of the flags and what they do.

**Comment by arberx** [comment]
Makes sense. My apologies.

**Comment by nathanhleung** [comment]
I arrived here because of the same issue. Worthwhile to put something in the README because of this? Happy to make a PR.
