### ISSUE TITLE
Specify descriptor source in addition to server reflection

### ISSUE THREAD

**Issue by alexanderchiu** [fullstorydev/grpcurl#135]
Hi

I have a use case where I have a RPC that make use of https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto for a metadata field.

Using server reflection, I'm unable to invoke the RPC with a JSON payload (including some specific metadata message). I can get this to work using the protoset/protofile approach, but that involves specifying many descriptor sources that are already available via server reflection. It would be great to be able to specify a set of descriptor sources that are used in _addition_ to the ones inferred from server reflection.

I'm happy to contribute a fix, if there is agreement that this is something useful.

**Comment by jhump** [comment]
@alexanderchiu, are you trying to create an `Any` for a message type that the server does not know about?

If the server knows about the message type, it _should_ work when using server reflection. The JSON decoding used in `grpcurl` will query the server for a descriptor for the named message type when resolving/parsing `Any` messages.

**Comment by alexanderchiu** [comment]
Thanks for getting back to me so quickly @jhump. Yes, I am using a message type that the server does not know about. On the back end the server actually just passes it off to another application that knows how to decode the message.

**Comment by jhump** [comment]
@alexanderchiu, okay. In that case, what you describe (extra descriptors or proto sources, just for resolving message types put into an `Any`) might be useful.

Though I wonder also about providing some fallback support for unknown `Any` types, like allowing you to put a binary-encoded blob there.

FWIW, we have this for _showing_ `Any` messages with unrecognized types, in response messages. For those, `grpcurl` emits a JSON object with `@type`, `@value`, and `@error` attributes where `@value` is base64-encoded bytes of binary-encoded proto and `@error` indicates that there was an error resolving the given message type.

So maybe it would be nice to be able to parse a similar format -- where you could put the contents into a field named `@value`. I guess the actual value to put there would be gross to construct. You would need to use `protoc -encode=<message>` and then interpolate that into your request body (or something similar).

**Comment by alexanderchiu** [comment]
> @alexanderchiu, okay. In that case, what you describe (extra descriptors or proto sources, just for resolving message types put into an Any) might be useful.

Ok great. I'll try add this functionality and tests when I have some free time.

> FWIW, we have this for showing Any messages with unrecognized types, in response messages. For those, grpcurl emits a JSON object with @type, @value, and @error attributes where @value is base64-encoded bytes of binary-encoded proto and @error indicates that there was an error resolving the given message type.
