### ISSUE TITLE
Return Error Message instead of printing the error message.

### ISSUE THREAD

**Issue by Prithvirajbilla** [fullstorydev/grpcurl#138]
Currently, whenever the error status is not status.OK, grpcurl just writes error message to console. It would be better if it returned the error message instead of writing to console. (similar to the success case).

Link to the code: https://github.com/fullstorydev/grpcurl/blob/0d669e78d0cd1439757f2faa6717e3786228bc86/cmd/grpcurl/grpcurl.go#L587

I am building grpc powershell client using grpcurl and it would make it more easier if the behavior is same for both success and error condition.

The change I am proposing is, just return the error message - instead of printing it console.

**Comment by jhump** [comment]
What does it mean to "just return the error message"? This is a command-line program; an invocation cannot return anything but an 8 bit status code.

**Comment by Prithvirajbilla** [comment]
@jhump sorry for the confusion. you are right.  (closing the ticket)

I got confused working with powershell scripts. as powershell scripts can throw native exceptions and other powershell scripts can natively catch them.
