### ISSUE TITLE
Release 1.5.0 Seems to Use gRPC 1.27

### ISSUE THREAD

**Issue by gnossen** [fullstorydev/grpcurl#139]
We're testing out grpcurl 1.5.0 with the xDS scheme and found that things don't work quite as we expect.

```
rbellevi@rbellevi-xds-python-testing:~/grpc$ cat xds_bootstrap.json 
{
  "node": {
    "id": "rbellevi-xds-python-testing"
  },
  "xds_servers": [{
    "server_uri": "xdsserver.test.com:443",
    "channel_creds": [
      {
        "type": "google_default",
        "config": {}
      }
    ]
  }]
}
```

```
rbellevi@rbellevi-xds-python-testing:~/grpc$ GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info ./grpcurl -d '{}' xds-experimental:
///test-backend-service-rbellevi7 grpc.testing.TestService/UnaryCall
INFO: 2020/03/18 00:27:40 parsed scheme: "xds-experimental"
INFO: 2020/03/18 00:27:40 ccResolverWrapper: sending update to cc: {[] 0xc0000c3660}
INFO: 2020/03/18 00:27:40 ClientConn switching balancer to "xds_experimental"
INFO: 2020/03/18 00:27:40 xds: Reading bootstrap file from xds_bootstrap.json
WARNING: 2020/03/18 00:27:40 xds: unexpected data in bootstrap file: {xds_servers, [{
    "server_uri": "xdsserver.test.com:443",
    "channel_creds": [
      {
        "type": "google_default",
        "config": {}
      }
    ]
  }]}
INFO: 2020/03/18 00:27:40 parsed scheme: ""
INFO: 2020/03/18 00:27:40 scheme "" not registered, fallback to default scheme
INFO: 2020/03/18 00:27:40 ccResolverWrapper: sending update to cc: {[{ 0  <nil>}] <nil>}
INFO: 2020/03/18 00:27:40 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2020/03/18 00:27:40 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0ab0, CONNECTING
WARNING: 2020/03/18 00:27:40 grpc: addrConn.createTransport failed to connect to { 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: missing address". Reconnecting...
INFO: 2020/03/18 00:27:40 pickfirstBalancer: HandleSubConnStateChange: 0xc0001e0ab0, TRANSIENT_FAILURE
Failed to dial target host "xds-experimental:///test-backend-service-rbellevi7": dial tcp: missing address
```

We've also found that building from master does not result in this error.

The crucial bit is this log:
```
WARNING: 2020/03/18 00:27:40 xds: unexpected data in bootstrap file
```

This warning message was [present in 1.27](https://github.com/grpc/grpc-go/blob/v1.27.0/xds/internal/client/bootstrap/bootstrap.go#L148), but not 1.28:

```
rbellevi@rbell:~/Dev/grpc-go$ git checkout v1.27.0
Previous HEAD position was 14218288 Change version to 1.28.0 (#3426)
HEAD is now at a89bee78 Change version to 1.27.0 (#3340)
rbellevi@rbell:~/Dev/grpc-go$ grep -rn "unexpected data"
xds/internal/client/bootstrap/bootstrap.go:148:                 grpclog.Warningf("xds: unexpected data in bootstrap file: {%v, %v}", k, string(v))
rbellevi@rbell:~/Dev/grpc-go$ git checkout v1.28.0
Previous HEAD position was a89bee78 Change version to 1.27.0 (#3340)
HEAD is now at 14218288 Change version to 1.28.0 (#3426)
rbellevi@rbell:~/Dev/grpc-go$ grep -rn "unexpected data"
rbellevi@rbell:~/Dev/grpc-go$ 
```
Theoretically, based on its [`go.mod`](https://github.com/fullstorydev/grpcurl/blob/96cfd48e323d76f0ccc611445b5640cabc9581ea/go.mod#L7), 1.5.0 should have been using gRPC 1.28. Do you have any insight into the build process for the uploaded artifacts that might explain this?

@jhump

**Comment by jhump** [comment]
I've deleted the uploaded artifacts. Something definitely went wrong. I'm also still struggling with getting `brew bump-formula-pr` to work, for that aspect of the release.

I don't release often enough to remember everything, and all the steps are not well documented. (I am actually working on a branch now to add directions plus automation/scripts to make sure this doesn't get botched in the future.) Anyhow, I will get it sorted it out soon I think.

BTW, can you try the docker image? I think that was built fine and should work as you expect. Please let know. (I have no ability to test the xDS stuff, so I've only been able to do the most basic of smoke tests.)

**Comment by gnossen** [comment]
No worries. I've had to delete a fair few releases myself. I'll try out the docker image. I'll get back to you on that soon.

**Comment by jhump** [comment]
I just rebuilt and re-uploaded release binaries. Please let me know if they look okay.

For work, we have some code stuck on Go 1.11 and not using modules (for App Engine, and using `GO111MODULE=off`). I accidentally had that env var set when I ran `make release`, so it just used the version of the dependencies that I already had checked out under my `GOPATH` :(

**Comment by gnossen** [comment]
Haven't managed to get the docker image to a point where I can adequately test it yet. But I have repulled the Github release:

```
rbellevi@rbellevi-xds-python-testing:~/grpc$ wget https://github.com/fullstorydev/grpcurl/releases/download/v1.5.0/grpcurl_1.5.0_linux_x86_64.tar.gz
--2020-03-18 00:57:07--  https://github.com/fullstorydev/grpcurl/releases/download/v1.5.0/grpcurl_1.5.0_linux_x86_64.tar.gz
2020-03-18 00:57:08 (8.27 MB/s) - ‘grpcurl_1.5.0_linux_x86_64.tar.gz’ saved [4603773/4603773]
rbellevi@rbellevi-xds-python-testing:~/grpc$ tar xzvf grpcurl_1.5.0_linux_x86_64.tar.gz
rbellevi@rbellevi-xds-python-testing:~/grpc$ GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info ./grpcurl -d '{}' xds-experimental:///test-backend-service-rbellevi7 grpc.testing.TestService/UnaryCall
INFO: 2020/03/18 00:57:38 parsed scheme: "xds-experimental"
INFO: 2020/03/18 00:57:38 ccResolverWrapper: sending update to cc: {[] 0xc00000b6a0}
INFO: 2020/03/18 00:57:38 ClientConn switching balancer to "xds_experimental"
INFO: 2020/03/18 00:57:38 xds: Reading bootstrap file from xds_bootstrap.json
WARNING: 2020/03/18 00:57:38 xds: unexpected data in bootstrap file: {xds_servers, [{
    "server_uri": "xdsserver.test.com:443",
    "channel_creds": [
      {
        "type": "google_default",
        "config": {}
      }
    ]
  }]}
INFO: 2020/03/18 00:57:38 parsed scheme: ""
INFO: 2020/03/18 00:57:38 scheme "" not registered, fallback to default scheme
INFO: 2020/03/18 00:57:38 ccResolverWrapper: sending update to cc: {[{ 0  <nil>}] <nil>}
INFO: 2020/03/18 00:57:38 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2020/03/18 00:57:38 pickfirstBalancer: HandleSubConnStateChange: 0xc0001c0c50, CONNECTING
WARNING: 2020/03/18 00:57:38 grpc: addrConn.createTransport failed to connect to { 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: missing address". Reconnecting...
INFO: 2020/03/18 00:57:38 pickfirstBalancer: HandleSubConnStateChange: 0xc0001c0c50, TRANSIENT_FAILURE
Failed to dial target host "xds-experimental:///test-backend-service-rbellevi7": dial tcp: missing address
```
Looks like it's still the same problem. It's possible we're pulling from a proxy cache, though?

As a simple litmus test, I think this command will suffice: `strings ./grpcurl | grep "unexpected data in bootstrap file"`. This produces a bunch of output for the uploaded artifacts and none from my from-source build on master.

**Comment by gnossen** [comment]
@jhump I can confirm that the docker image is working correctly.

**Comment by jhump** [comment]
@gnossen, I think I finally got it. Sorry for the false starts. I know -- it's amateur hour around here... 

Anyhow, hopefully #140 will help me to not screw up future releases...

I did the `strings ... | grep ...` command above and found no such occurrences in the compiled binaries.

**Comment by gnossen** [comment]
@jhump Thanks for all of the effort on this. The latest upload is working exactly as intended. I really appreciate how responsive and helpful you've been. 😃
