### ISSUE TITLE
Include headers on discovery calls

### ISSUE THREAD

**Issue by FreGalle** [fullstorydev/grpcurl#14]
Headers are currently not sent along with service/method discovery calls. This prevents grpcurl from being used with any server that for example performs custom header-based authentication.

Any particular reasoning behind the decision not to send headers with the discovery calls? I think it would be sensible for any server performing (custom) authentication/authorization before executing a service call to extend the auth to the discovery of its services.

**Comment by jhump** [comment]
That seems reasonable. I think it should be behind a command-line option -- either a flag that indicates that metadata should accompany service reflection requests or options to specify a separate set of headers just for the reflection calls. I think the former would be the simplest approach.

If you want to take a crack at a PR, I'll take a look.

**Comment by FreGalle** [comment]
Sure, I'll have a look and probably open a PR later this week.
