### ISSUE TITLE
Read input from file (consistency with `curl -d`)

### ISSUE THREAD

**Issue by l3ender** [fullstorydev/grpcurl#141]
If I have a JSON file that represents my request, is it possible to pass it to `grpcurl` as an input, like curl's `-d` flag?

```
grpcurl -d @test.json grpc.server.com:443 my.custom.server.Service/Method
```

**Comment by jhump** [comment]
You can achieve that today in a couple of ways:
```
grpcurl -d @ grpc.server.com:443 my.custom.server.Service/Method <test.json
grpcurl -d "`cat test.json`" grpc.server.com:443 my.custom.server.Service/Method
```

**Comment by l3ender** [comment]
Thanks much for the quick response!

I'm getting the following error when trying to do either method, could you advise?

```
Error invoking method "my.custom.server.Service/Method": error getting request data: illegal base64 data at input byte 0
```

Here's my test file:

```json
{
	"request": {
		"headers": {
    		"key": "Accept",
    		"value": "*/*"
		},
		"raw_body": "{\n\t\"test\": \"test\"\n}\n"
	}
}
```

I think it might have to do with escaping the tab and newline characters in the `raw_body` field, but I can't seem to get it right. I'm using iTerm on a Mac.

**Comment by l3ender** [comment]
I realized this has to do with the proto definition using `bytes` (truncated for brevity):

```proto
message Object {
  ...
  MiniRequestObject request = 3;
}
message MiniRequestObject {
  ...
  bytes raw_body = 14;
}
```

Is there a way to provide this type of field to grpcurl?

**Comment by jhump** [comment]
Bytes fields are provided as base64-encoded strings, which is why the error was complaining that the input had illegal base64 data.

**Comment by l3ender** [comment]
Thanks for the help! I'll close the issue as I am able to accomplish what I want.

It may help future users to have the example using a file as input included in the readme. Just my two cents.

Thanks again!
