### ISSUE TITLE
is there a version for arm?

### ISSUE THREAD

**Issue by gdonlyathw** [fullstorydev/grpcurl#143]
is there a version for arm?
if not, how do i to build for arm?

**Comment by jhump** [comment]
Not currently. You can build one using the Go compiler's cross-compile support. If you are building on an arm device, you can just get this repo and run `make install` (requires having Go installed first). If you are building on another machine and targeting arm, set your `GOOS` and `GOARCH` environment variables and then run `make install`. That will enable Go's cross-compiler support. (See more details in this old blog post: https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5)

**Comment by jhump** [comment]
Addressed in a contribution #220 

And now the first release is available that includes a pre-built arm64 binary: [v1.8.1](https://github.com/fullstorydev/grpcurl/releases/tag/v1.8.1)
