### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by notetook** [fullstorydev/grpcurl#148]
Like curl `-L` option, is there any option to follow redirect?

I think there is no option for redirect, so just throw error like
`Failed to list services: rpc error: code = Unknown desc =`

**Comment by jhump** [comment]
@notetook, 3xx response codes are not valid response codes with gRPC. While the underlying transport is HTTP/2, a gRPC client is _not_ meant to be a full HTTP client -- things like cookies and redirects for example are not part of gRPC.

While a better error message would be a valid improvement to grpcurl, I don't think following redirects is. I hope that makes sense.

**Comment by notetook** [comment]
@jhump 
I don't have a good understanding of gRPC protocol. So your reply is good opportunity to study grpc for me.
but i think it is nice idea to improve or elaborate error logs. Anyways, thx for your explain.
