### ISSUE TITLE
any incompatible changes?

### ISSUE THREAD

**Issue by m-liaee** [fullstorydev/grpcurl#151]
I am recently try to build a project which I had build it multiple times successfully. But recently I get this error while building grpcurl as part of build process, is there any imcompatible changes made to your repo?
\# Build grpcurl
go get github.com/fullstorydev/grpcurl
\# google.golang.org/protobuf/proto
/root/go/src/google.golang.org/protobuf/proto/proto_methods.go:18:23: cannot use m.ProtoMethods() (type *protoreflect.Message) as type *struct ...

**Comment by jhump** [comment]
Sorry @m-liaee but that's not enough info for me to go on.

That compile error is in google.golang.org/protobuf/proto, not in grpcurl. Maybe it's some other incompatibility between a dependency shared by grpcurl and the proto library? Is there more to the message that is cut off with that trailing "..."?

Also, what version of Go are you using? Are you using Go modules? If so, are you running `go get ...` from in a Go module that already depends on particular versions of the protobuf or grpc runtime packages?

This library is built in CI against latest version of all dependencies (that's the `GO111MODULE=off` configs in Travis for both Go 1.11 and Go 1.12). And, aside from something I had to fix today (which fixed a `staticcheck` linter error), it's been green for quite some time.

I do know that the protobuf team recently landed lots of changes to `github.com/golang/protobuf`, and the newest version depends on `google.golang.org/protobuf` (the latter package is a new "API v2", which uses a different import path).

Those newest proto versions _have_ introduced some incompatible changes. Though I don't know of any _compile-time_ incompatibilities. Most of the troubles I've seen are only if you're doing things "off the beaten path" and manifest as `go vet` failures or as runtime errors and panics.
