### ISSUE TITLE
Are error details of types within the import path expected to be decoded?

### ISSUE THREAD

**Issue by cpick** [fullstorydev/grpcurl#152]
Thanks for all your work on such a great tool!

I'm using `grpcurl -version` "grpcurl 1.5.0" and have noticed that since 1.3.0 there's support for showing any error details from the response.  What I can't tell from [the release notes](https://github.com/fullstorydev/grpcurl/releases/tag/v1.3.0) or the [original](https://github.com/fullstorydev/grpcurl/issues/96) [tickets](https://github.com/fullstorydev/grpcurl/pull/98) is whether I should expect `grpcurl` to be able to decode and pretty-print types that are included in proto files within the include path?

For example (where `git -C ~/src/google-api-common-protos remote get-url origin` is "git@github.com:googleapis/api-common-protos.git" which contains "google/rpc/error_details.proto"):

```sh
$ grpcurl -plaintext -import-path ~/src/google-api-common-protos -proto ~/src/foosvc/foosvc.proto localhost:8082 my.foosvc.Foosvc/Foo
ERROR:
  Code: InvalidArgument
  Message: There was an error processing the request
  Details:
  1)	{
    	  "@error": "google.rpc.ErrorInfo is not recognized; see @value for raw binary message data",
    	  "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    	  "@value": "<elided base64-encoded value>"
    	}
  2)	{
    	  "@error": "google.rpc.BadRequest is not recognized; see @value for raw binary message data",
    	  "@type": "type.googleapis.com/google.rpc.BadRequest",
    	  "@value": "<elided base64-encoded value>"
    	}
  3)	{
    	  "@error": "google.rpc.DebugInfo is not recognized; see @value for raw binary message data",
    	  "@type": "type.googleapis.com/google.rpc.DebugInfo",
    	  "@value": "<elided base64-encoded value>"
    	}
```

Is this working as expected? Is there some other setting I could use to help `grpcurl` decode these values?  Thanks!

**Comment by jhump** [comment]
Hi, @cpick! Great question.

As it turns out this _is_ the expected behavior... sort of.

If the given message type (e.g. `google.rpc.ErrorInfo`) is not recognized, this is what it prints. If you were using server reflection, and the server knows about the message type, then it would print correctly. (It is possible that the server does _not_ know about the message type if it is proxying an error response from another server -- such that the _other_ server generated these `Any` messages and knows of the enclosed type, but the actual server replying to `grpcurl` does not.)

However, when using `-proto` to specify the RPC schema details, you need to also provide `-proto` sources for those error types. So, in this case, you'd need to add command-line args to point `grpcurl` at the various Google-provided protos that define those types (which can be found [here](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto)).

**Comment by cpick** [comment]
> However, when using -proto to specify the RPC schema details, you need to also provide -proto sources for those error types. So, in this case, you'd need to add command-line args to point grpcurl at the various Google-provided protos that define those types (which can be found here).

You're exactly right if I add `-proto ~/src/google-api-common-protos/google/rpc/error_details.proto` to my above command it works as I'd hoped:
```sh
$ grpcurl -plaintext -import-path ~/src/google-api-common-protos -proto ~/src/google-api-common-protos/google/rpc/error_details.proto -proto ~/src/foosvc/foosvc.proto localhost:8082 my.foosvc.Foosvc/Foo
ERROR:
  Code: InvalidArgument
  Message: There was an error processing the request
  Details:
  1)	{
    	  "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    	  "domain": "foo.bar",
    	  "reason": "BAD_REQUEST"
    	}
...
```

What was/is surprising to me is that since I'd already added "~/src/google-api-common-protos" as an import path I didn't realize that I needed to explicitly add the exact proto file within that path ("~/src/google-api-common-protos/google/rpc/error_details.proto"), but now that I know that I can it works great.

It may still be nice if supplying just an import-path would work, but this gets the job done for me.  If that doesn't sound like a useful addition I'm happy to close out this ticket.

Thanks for your quick and helpful reply!

**Comment by jhump** [comment]
> I'd already added `~/src/google-api-common-protos` as an import path

But did any of the proto files you named in `-proto` options actually _import_ anything from there?

The import paths are not used to eagerly consume all proto files therein. They are just used to resolve `import` statements in the filenames you tell it (just like in `protoc`). If you add the following statement to one of your source files, then I believe it would work as you were expecting:
```proto
import "google/rpc/error_details.proto";
```
That way, it is an explicit dependency and it _will_ parse that file without you having to name the file in a `-proto` option.

**Comment by cpick** [comment]
> But did any of the proto files you named in -proto options actually import anything from there?
Ahh, the `foosvc.proto` file I named in `-proto` did import other packages within the google hierarchy, but not `google/rpc/error_details.proto`.

That explains it, thanks.
