### ISSUE TITLE
How to install the grpcurl binary on Linux?

### ISSUE THREAD

**Issue by jianzhangbjz** [fullstorydev/grpcurl#154]
I look through this section https://github.com/fullstorydev/grpcurl#binaries, must I build it by myself? The below is the process of the installation, but I don't think it a good way.
```console
# wget https://github.com/fullstorydev/grpcurl/archive/v1.5.1.tar.gz
# tar -zxvf v1.5.1.tar.gz
# cd grpcurl-1.5.1/cmd/grpcurl/
# go build
# ls
go1_10.go  go1_9.go  grpcurl  grpcurl.go  indent_test.go  unix.go
```
So, how to install it by `yum`? Thanks!

**Comment by jhump** [comment]
The GitHub releases include built binaries: https://github.com/fullstorydev/grpcurl/releases
You won't find one for 1.5.1. Use 1.5.0. (You can see the release notes for why.)

**Comment by alfonmga** [comment]
This how I provisionate an Ubuntu server to have installed `grpcurl`:

```bash
#!/bin/bash

# Install grpcurl if not installed
if ! command -v grpcurl >/dev/null 2>&1; then
    curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.6/grpcurl_1.8.6_linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin
fi
```

**Comment by murfel** [comment]
Addition to the previous comment: 1) for new release 2) run the second command from sudo

```
curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz" | sudo tar -xz -C /usr/local/bin
```

**Comment by scottstensland** [comment]
as per README on this repo

```
go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
```
