### ISSUE TITLE
Go get failing

### ISSUE THREAD

**Issue by shettyh** [fullstorydev/grpcurl#16]
Go get is failing with this error

\# github.com/jhump/protoreflect/dynamic
../../../github.com/jhump/protoreflect/dynamic/json.go:960: undefined: jsonpb.AnyResolver
../../../github.com/jhump/protoreflect/dynamic/json.go:968: undefined: jsonpb.AnyResolver

**Comment by jhump** [comment]
@shettyh, you need to update the version of `github.com/golang/protobuf` you are using.
