### ISSUE TITLE
How to provide server username and password with this client 

### ISSUE THREAD

**Issue by vipkum2** [fullstorydev/grpcurl#163]
I want to access my GRPC server with username and password.
I could not find a way to provide the same.
kindly help.

**Comment by jhump** [comment]
gRPC does not have a standard username/password auth mechanism.

Are you just using `Authorization` headers? If you are and you're also doing `Basic` as the auth mechanism, you would add this as a header:

```
# this prompts: enter credentials in "username:password" format
read CREDS
export CREDS
grpcurl -expand-headers \
    -H 'Authorization: Basic ${CREDS}' \
    server.name:8080 list
```

If you use some other mechanism for authn, you'll need to reproduce the metadata that successfully authenticates you and supply that to the server using the correct metadata header format.

**Comment by vipkum2** [comment]
Thanks @jhump for helping me!
But It did not seem to work. I have another command line grpc client and in that we can provide the user:password. 
Our server implemented in way that it can authorize by user:pwd and as well with certificates.
consider I have server ip: 1.1.1.1, port: 10161: I have tried many times , but i think i am doing something wrong:
./grpcurl -v -expand-headers -H 'Authorization:Basic {"ABC":"ABC"}' 1.1.1.1:10161 list -insecure
 ./grpcurl -v -expand-headers -H 'Authorization:Basic {"ABC":"ABC"}' 1.1.1.1:10161 list
 ./grpcurl -v -expand-headers -H 'Authorization:{"ABC":"ABC"}' 1.1.1.1:10161 list
 ./grpcurl -v -expand-headers -H 'Authorization:{ABC:ABC}' 1.1.1.1:10161 list
 CRED={ABC:ABC}
 $CRED
 echo $CRED
 ./grpcurl -v -expand-headers -H 'Authorization:Basic ${CRED}' 1.1.1.1:10161 list
 import CRED
 export CRED
 ./grpcurl -v -expand-headers -H 'Authorization:Basic ${CRED}' 1.1.1.1:10161 list
 echo CRED
 echo $CRED
 echo ${CRED}
 CRED=ABC:ABC
 echo ${CRED}
 import CRED
 export CRED
 ./grpcurl -v -expand-headers -H 'Authorization: Basic ${CRED}' 1.1.1.1:10161 list
 ./grpcurl -v -expand-headers -H 'Authorization: ABC:ABC' 1.1.1.1:10161 list
 ./grpcurl -v -expand-headers -H 'ABC:ABC' 1.1.1.1:10161 list
 ./grpcurl -v -expand-headers -H "ABC":"ABC" 1.1.1.1:10161 list
 ./grpcurl -v -expand-headers -H ABC:ABC 1.1.1.1:10161 list

**Comment by vipkum2** [comment]
Tried with certificate as well, but unable to login:
hax-vipkumar-1|/localdisk/gitRepo$ ./grpcurl 1.1.1.1:10161 list -key usercert.key  -cert usercert.crt Too many arguments.
Try './grpcurl -help' for more details.

**Comment by jhump** [comment]
For the authorization header attempts, were you trying to pass a literal string like "user:pass" in the header? It needs to be base64-encoded. I see that I totally missed that from my example. I apologize -- I thought I had it in there and must have removed it when I was trying to formulate it so that you don't need to pass credentials as command-line args (since that is a possible security problem).

My apologies. So try `CREDS=$(echo -n $CREDS | base64)` before supplying the resulting base64-encoded value to grpcurl. Note that it is very important that the base64-encoded data _not_ have a newline encoded at the end. That's also why the formulation above uses `read`: that will read a line of input into an env var, but will _not_ include the trailing newline.

As for the certificate approach, options like `-key` and `-cert` must come _before_ positional arguments like the address and `list`. So just move those before and try again.

**Comment by vipkum2** [comment]
Thanks again to help!
Now I am able to access the server via certificate. But our server does not support reflection API.
So let say I have 1 path /cpu/usage, now how can I Get the data for this path.

And How to start streaming/subscription with this client.

**Comment by jhump** [comment]
> how can I Get the data for this path

If the service does not support reflection, you must have access to the proto source files that define the RPC schema. Then use `-proto` and `-import-path` arguments to tell grpcurl how to load the proto sources.

> And How to start streaming/subscription with this client.

Invoking the tool starts the stream. It will block until it sees end of stream from the server. Note, however, that it also half-closes the stream after sending messages. If you don't tell it what messages to send, it will immediately half-close (and the server may then immediately close). You can use `-d @` to have it read input stream messages from stdin. That will keep the stream completely open until it sees EOF from stdin.

Take a look at the demo of grpcurl I gave at Gophercon the other year: https://www.youtube.com/watch?v=dDr-8kbMnaw (towards the end). The demo shows how bi-directional streams can work with grpcurl.

**Comment by vipkum2** [comment]
Thank you very much for all your help!

I am able to use the same.
