### ISSUE TITLE
grpcurl doesn't build with protobuf 1.4.0

### ISSUE THREAD

**Issue by bartle-stripe** [fullstorydev/grpcurl#171]
https://github.com/golang/protobuf/commit/cc376d7145c679febdd10557ded10ff26a681fbb#diff-ccd89ccdf362c7588f4a52de7378bde0 (part of 1.4.0) moved jsonpb_test_proto to an internal package.  It seems like the easiest thing would be to create a test proto in this project that copied https://github.com/golang/protobuf/blob/v1.3.5/jsonpb/jsonpb_test_proto/test_objects.proto#L139?

**Comment by jhump** [comment]
Hi @bartle-stripe. I think you are looking at an old version of the code. CI runs the tests against latest of the Go protobuf runtime, and it is passing. The particular issue you describe was fixed months ago in #145.

**Comment by bartle-stripe** [comment]
Ah, you're right, I only noticed that https://github.com/fullstorydev/grpcurl/blob/master/go.mod#L6 hadn't been updated.
