### ISSUE TITLE
[cli][options]  Version information Not Properly Displayed

### ISSUE THREAD

**Issue by conradwt** [fullstorydev/grpcurl#175]
Given, I'm on macOS Big Sur Beta 2.  When I perform `grpcurl -version` within the terminal, then I'm seeing the following message:

```zsh
grpcurl dev build <no version set>
```

**Comment by jhump** [comment]
I assume you built this locally, vs. installing via `brew`, release artifacts in GitHub, or using the docker image?

If so, that is expected if you didn't supply the right metadata at build time. The version is not included in the source code -- it comes from version control metadata.

If you want a properly versioned binary, use the official releasees _or_ download/clone the repo and run `make install`.

**Comment by conradwt** [comment]
@jhump Thanks for the information and I was able to see the versioning information by performing a `make install`.  This issue can be closed.
