### ISSUE TITLE
grpc 1.31.0 removed xds/experimental package

### ISSUE THREAD

**Issue by johanbrandhorst** [fullstorydev/grpcurl#178]
Just a heads up, grpc-go 1.31.0 seems to have removed the `xds/experimental` package. I think it's just moved to the `xds` package so might be an easy update?

See https://github.com/grpc/grpc-go/commit/6e77a8b2f6a0c45a9fb9854734718482b827f6e5. This is causing go mod update failure in dependents of grpcurl (including grpcui).

**Comment by jhump** [comment]
@johanbrandhorst, thanks for the heads up. But this repo does not refer to `xds/experimental` anymore: #168 

I will go ahead update and release a version of `grpcui` to refer to the latest version of this repo, which should fix it there, too.

**Comment by johanbrandhorst** [comment]
Doh! Thanks for the correction.
