### ISSUE TITLE
Invalid memory access panic

### ISSUE THREAD

**Issue by pierreis** [fullstorydev/grpcurl#185]
When following the ProtoCat tutorial at [https://grissius.github.io/protocat/docs/wiki/starting-server](https://grissius.github.io/protocat/docs/wiki/starting-server), I am running into the following panic when using grpcurl

```bash
$ grpcurl \
    -proto cat.proto \
    -plaintext \
    -d '{"name": "ProtoCat"}' \
    localhost:3000 cats.v1.CatRegister.GetCat
Failed to process proto source files.: could not parse given files: %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)

$ grpcurl --version
grpcurl 1.7.0
```

On MacOS, from Homebrew.

**Comment by pierreis** [comment]
The issue seems to be solved on `master` ; the panic disappeared.
Closing the issue.

**Comment by jhump** [comment]
Could you provide the source for `cat.proto`, maybe in a [gist](gist.github.com)?
