### ISSUE TITLE
Crashes on file not found

### ISSUE THREAD

**Issue by walles** [fullstorydev/grpcurl#190]
```
~ $ grpcurl --version
grpcurl 1.7.0
~ $ grpcurl -proto x y z
Failed to process proto source files.: could not parse given files: %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
~ [1] $
```

Instead of `invalid memory address or nil pointer dereference` I think it would be better if `gcurl` said something along the lines of `Protocol file not found: x`.

**Comment by jhump** [comment]
I think this panic was a bug in the jhump/protoreflect library grpcurl imports that has since been fixed.

The latest version of grpcurl reports a better error message:
```
Failed to process proto source files.: could not parse given files: open x: no such file or directory
```
