### ISSUE TITLE
Too many arguments.

### ISSUE THREAD

**Issue by bytegriffin** [fullstorydev/grpcurl#195]
message.proto：
`message HelloRequest {
  string name = 1;
}

message HelloResponse {
  int32 code=1;
  string message = 2;
}

service Hello {
  rpc SayHello(HelloRequest) returns (HelloResponse);
}
`

command：
`grpcurl -plaintext -d '{"name": "gopher"}' 127.0.0.1:8080 Hello/SayHello`

Error：
Too many arguments.
Try 'grpcurl -help' for more details.

why？

**Comment by jhump** [comment]
What shell are you using? I'm going to guess there's something wrong with the quotes/escaping of the `-d` argument, such that it thinks that `'{"name":` is a different argument from `"gopher"}'`. The entire request needs to be sent to the program as a single argument. You can also try directing the contents to `grpcurl`'s stdin, and using `-d @`.

**Comment by bytegriffin** [comment]
My dev enviroment:
Windows 10，Goland(2020.2) Terminal
I use go tool to install grpcurl：
`
go get github.com/fullstorydev/grpcurl/...
go install github.com/fullstorydev/grpcurl/cmd/grpcurl
`

**Comment by jhump** [comment]
This looks to be specific to Windows terminal, which has its own weird way of quoting spaces. Let me Google that for you:
https://stackoverflow.com/questions/28939980/passing-json-string-via-command-line
So you should try this instead:
```
grpcurl -plaintext -d "{\"name\": \"gopher\"}" 127.0.0.1:8080 Hello/SayHello
```

**Comment by bytegriffin** [comment]
Thanks, it works!
