### ISSUE TITLE
Question: Does grpcurl close its connections at the end of its run?

### ISSUE THREAD

**Issue by skincell** [fullstorydev/grpcurl#196]
Please let me know if there is a better place to put this question. 

Does grpcurl close its connections at the end of running it from the command line? 

The gRPC service seems to freeze/start refusing my connections after several queries from grpcurl.

Thanks!

**Comment by jhump** [comment]
It should. After the connection is dialed, any calls to exit the process will close the connection, which will abort any active RPCs. However, it looks like this cleanup may not happen if the process is killed. Is it possible that the processes were stopped via something like ctrl+C (which would send a SIGINT signal to the process). However, I think most of the cases where the process is terminated via signal should also do some amount of cleanup.

Perhaps there is some other bug in the server that is not correctly noticing an RPC ending/stream being closed or not properly releasing resources.

**Comment by skincell** [comment]
Thank you for your quick response.
