### ISSUE TITLE
Temporary Redirect: HTTP status code 307; transport: missing content-type field

### ISSUE THREAD

**Issue by gkarnik05** [fullstorydev/grpcurl#201]
I'm exposing asp.net 3.1 webapi through gRPC. I get the below error message while trying to describe the available methods. 

`grpcurl -H "content-type: application/grpc" -H "Authorization: Bearer <token>" -connect-timeout 30 -plaintext localhost:5701 describe
Failed to list services: rpc error: code = Unknown desc = Temporary Redirect: HTTP status code 307; transport: missing content-type field`

Is this because of missing content-type field in response headers?

**Comment by jhump** [comment]
While gRPC may use HTTP/2 as a transport, a gRPC client is _not_ a full-featured HTTP client. So gRPC clients do not respect redirects, and they expect "content-type" as a response header for all responses ([spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)).

So I think you need to figure out why the server is issuing a redirect and then craft a request that will not result in a redirect, possibly through the use of additional headers?
