### ISSUE TITLE
Proto generation

### ISSUE THREAD

**Issue by wahmedswl** [fullstorydev/grpcurl#206]
Hi, can we export proto from grpc server reflection? 

Thanks

**Comment by jhump** [comment]
@wahmedswl, yes. Run `grpcurl -h` and then take a look at the `-protoset-out`. Note, however, that this exports a [`FileDescriptorSet`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L57) that is written in the binary protobuf format. It does not produce proto sources.

Though you could use the packages in https://github.com/jhump/protoreflect to translate them into source files. You'd have to write some Go code to make that happen.

* Read the contents of the output descriptor set file and unmarshal into a [`*descriptorpb.FileDescriptorSet`](https://pkg.go.dev/google.golang.org/protobuf/types/descriptorpb#FileDescriptorSet)
* Call [`desc.CreateFileDescriptorsFromSet`](https://godoc.org/github.com/jhump/protoreflect/desc#CreateFileDescriptorsFromSet) to turn that into a set of "rich" descriptors.
* Create a [`*protoprint.Printer`](https://godoc.org/github.com/jhump/protoreflect/desc/protoprint#Printer) and use its `PrintProtoFile` method to generate proto source from each "rich" descriptor.

**Comment by wahmedswl** [comment]
Nice, can this be integrated within grpcurl? This is something useful.

Thanks

**Comment by jhump** [comment]
@costela, I'm not sure that would really work. The resulting source would not be compile-able unless it emitted, at a minimum, one file per referenced package. IMO, it would ideally be one file per actual input source file that defined the schema, which is how `-protoset-out` works.

So it needs to be special-cased to support multi-file export; it's not sufficient to just print the transitive closure of all elements independently as if in one file. I'm thinking that it would instead be a `-proto-out` option, where the resulting output will be a ZIP file, with possibly multiple proto source files inside.

**Comment by Eitol** [comment]
@costela @jhump @wahmedswl  I have made a PR to support this functionality. Check: #475
