### ISSUE TITLE
Using it as a library

### ISSUE THREAD

**Issue by anandsunderraman** [fullstorydev/grpcurl#208]
Is there a way I can use this as a library from a go program ?
If yes can you point me at an example or documentation or pointers on how I can do the same ?

**Comment by jhump** [comment]
You can indeed use it as a library. What are you hoping to accomplish or hoping that the library might do?

There is Go doc [here](https://pkg.go.dev/github.com/fullstorydev/grpcurl), which describes the exported API of the package you might link into your Go program. I know that Uber's [prototool](https://github.com/uber/prototool/blob/bd23eea89cb80720942bab4149077aca35d03c98/go.mod#L7) uses this repo as a library. You might also take a look at `grpcurl`'s [main package](https://github.com/fullstorydev/grpcurl/blob/master/cmd/grpcurl/grpcurl.go), which also of course makes use of the library:

**Comment by anandsunderraman** [comment]
I was looking to use it as part of my automated tests.
Goal was to provide the proto files, method name , service name as parameters and dynamically invoke the gRPC method
