### ISSUE TITLE
Why not installed grpcurl?

### ISSUE THREAD

**Issue by WalkWeb** [fullstorydev/grpcurl#216]
```
go version
go version go1.13.8 linux/amd64
```

```
go get github.com/fullstorydev/grpcurl/...
go install github.com/fullstorydev/grpcurl/cmd/grpcurl
grpcurl -help
grpcurl: command not found
```
No error, no install, why?

P.S. use Ubuntu 20.04

**Comment by jhump** [comment]
`go install ...` installs stuff in `$GOPATH/bin` or (if `GOPATH` env var not set) in `$HOME/go/bin`. You probably don't have that directory in your `PATH`.
