### ISSUE TITLE
How can i construct context info to my grpc api?

### ISSUE THREAD

**Issue by 1053611385** [fullstorydev/grpcurl#218]
My grpc server has context check to get some value, but i don't  konw how to set value to context,thank you!!!

**Comment by jhump** [comment]
I assume you are talking about a Go server. The gRPC runtime stores many things into the context, not all of them are controlled by the client.

I suspect you may be asking about request metadata, which servers can observe by querying them from the context. You can set these values with `grpcurl` using `-H` arguments. Try `grpcurl -h` to read more about that flag.
