### ISSUE TITLE
Is it okay to package grpcurl for Debian?

### ISSUE THREAD

**Issue by siyopao** [fullstorydev/grpcurl#222]
Hello 👋 

I was thinking to try to package grpcurl for Debian, and was just wondering if that would be okay?

Note that I have never packaged anything for Debian before, so I am unsure if I will be successful, or if it is even possible to package grpcurl, but I thought it may be nice to try.

Thank you!

**Comment by jhump** [comment]
To be honest, I don't know enough about Debian packages to know the effort involved in maintaining them and releasing new versions.

If it can't easily be automated (like in the existing `releasing/do-release.sh` script), then I have zero interest in supporting such a package as it's just more work whenever there is a release.

**Comment by siyopao** [comment]
Hi @jhump! Thanks for your reply. As far as I understand you will not need to do anything. The package will be maintained by myself and/or the debian-go-team, and hopefully a large part of that is indeed automated. So I guess my question was more-or-less if you had any moral objection.

In case it is okay to package, I did have one question though: in the package process it asks who is the tool's author. Who should I say?

Thanks!

**Comment by jhump** [comment]
Okay, thanks for the info. Please attribute the author as "FullStory, Inc.".

**Comment by siyopao** [comment]
Cool. Thanks! And thanks for gRPCurl!

**Comment by jhump** [comment]
@craigpastro, have you by chance created a debian package for grpcurl? This project got a request for one (#253). If there is a package available now, do you happen to know how we get it on [this page](https://repology.org/project/grpcurl/information)?

**Comment by craigpastro** [comment]
Hi @jhump. No, I'm sorry, I never got a chance to get around to it.

**Comment by jhump** [comment]
@craigpastro, no worries! I was just curious. Thanks for the update.
