### ISSUE TITLE
How to bypass TLS and still specify application/json type

### ISSUE THREAD

**Issue by kyprifog** [fullstorydev/grpcurl#231]
if I specify -plaintext to avoid TLS handshake error I get:

```
> grpcurl -proto hello.proto -plaintext -d '@' localhost:8080 
> {"name": "test"}
ERROR:
  Code: Unimplemented
  Message: Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
```
from my GRPC service no matter what headers I specify.  How do I specify application/grpc or application/grpc+json mime type while using `-plaintext` ?

**Comment by jhump** [comment]
The `-plaintext` option has nothing to do with content-type. Something else is wrong with your configuration. I suspect you're pointed at the wrong server or some sort of proxy, which is replying with an HTTP 404 and a plaintext response.

**Comment by kyprifog** [comment]
Awesome, thats what I was hoping you'd say, I think its a plaintext response that I didn't realize.
