### ISSUE TITLE
Unix Domain Socket on Windows

### ISSUE THREAD

**Issue by Rolice** [fullstorydev/grpcurl#244]
Hello,
Is there a reason why `-unix` flag is disabled on Windows? As I understand, this kind of support for local sockets was added in Windows 10, somewhere in 2018. Recently, I have cloned the project and allowed the flag and its usage in a custom build. The application behaves correctly and `bin\go_build_main.exe -plaintext -unix "*.sock" list` (also the direct method calls) work as expected.

The only change I have applied is to add `windows` target to the `+build` in `~\grpcurl\cmd\grpcurl\unix.go`:
```
// +build darwin dragonfly freebsd linux netbsd openbsd solaris windows
```

**Comment by DSanchen** [comment]
I would also like to have the -unix flag available on windows, but would rather rely on a binary...

**Comment by jhump** [comment]
Pull requests welcome.
