### ISSUE TITLE
Builds disabled in Travis CI

### ISSUE THREAD

**Issue by namrata-ibm** [fullstorydev/grpcurl#247]
It is observed that the builds for gRPCurl are temporarily disabled on [Travis ](https://travis-ci.com/github/fullstorydev/grpcurl) due to negative credit balance.

As per the Travis [blog](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis fully supports the OSS teams and allocate them more credits after they apply for same.
Could you please open a request with Travis CI support stating that you'd like to be considered for the OSS allotment?

More details on how to open support request with Travis can be checked [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

**Comment by namrata-ibm** [comment]
If needed, we can help follow up with Travis folks once request is raised.

**Comment by namrata-ibm** [comment]
@jhump Please let me know if there is any interest in Travis, or can I close the issue?

**Comment by jhump** [comment]
@namrata-ibm, thanks for the offer. But we use CircleCI for a lot of other things at FullStory, so I just moved this repo over to that in #256.
