### ISSUE TITLE
grpcurl not invoking method

### ISSUE THREAD

**Issue by ewolfman** [fullstorydev/grpcurl#252]
Hi,

I am using grpcurl 1.4.0.

In some cases grpcurl does not invoke certain grpc methods, seems like it remains open for input and is blocking.
For example if I do this:
```
grpcurl -d '{"name":"joe"}' -plaintext 127.0.0.1:5001 my.Service.TestMethod
```
The console simply gets stuck.

I know that I am reaching the correct service because if I make the following change ('name' changed to 'name1'):
```
grpcurl -d '{"name1":"joe"}' -plaintext 127.0.0.1:5001 my.Service.TestMethod
```
I will get an error from grpcurl that the service method "has no known field named name1".

Just to add that the service does work when invoked with other clients such as swagger or some other calling code.

Any idea why this gets stuck when invoking the service with the correct parameters?

Thanks.

**Comment by jhump** [comment]
Can you add logging to the server to confirm whether the server receives the request? If you use a `-max-time` argument, does it respect the timeout and if so what is the error? If it is "deadline exceeded", what do you see on the server side?

**Comment by ewolfman** [comment]
Hi,
It looks like the Grpc server configurer has a maxConcurrentCallsPerConnections set to 1.
Removing this seems to have solved the problem.
But, why is this causing grpcurl this behavior? is it dependent on concurrent calls per connection even for unary requests?
Thanks.

**Comment by jhump** [comment]
> is it dependent on concurrent calls per connection even for unary requests?

The server reflection feature uses a long-lived stream, which will be active concurrently with the RPC itself. If you allow 2 concurrent calls, it should work. Or if you provide proto sources to the tool via `-proto` (and `-import-path`) arguments, it would use only one concurrent call.

**Comment by ewolfman** [comment]
Would have been nice if this was not required...
Thanks for your answer.
