### ISSUE TITLE
Binary fields on -d option

### ISSUE THREAD

**Issue by uri200** [fullstorydev/grpcurl#266]
Hello, really cool project.

We would like to try `grpcurl` with `-d` argument using messages that contains binary fields

JSON does not support binary data. So normally is represented as base64 as seen below.
```
{
	"type": "directory_record",
	"deviceID": "IMSI001020000000064",
	"value":"eyJTZXJpYWxpemVkUmVwb3J0ZWRTdGF0ZSI6ImV5SnBaR1Z1ZEdsbWFXVnljeUk2SUhzaWMyZDNYMk5mZEdWcFpDSTZJQ0l4TWpBeU5Ea3lOelk0SW4wc0lDSnNiMk5oZEdsdmJsOW9hWE4wYjNKNUlqb2dXeUpsT0RobFpUaGpZeTFoWVRoaUxUUXhPRGt0T0dZeE5DMDBNV1E0TTJSbE9XTmxOR1VpWFN3Z0luQjVMMjlpYW1WamRDSTZJQ0p0WVdkdFlTNWthWEpsWTNSdmNubGtMbkp3WTE5elpYSjJhV05sY2k1RWFYSmxZM1J2Y25sU1pXTnZjbVFpZlE9PSIsIlZlcnNpb24iOjAsIlJlcG9ydGVySUQiOiJlODhlZThjYy1hYThiLTQxODktOGYxNC00MWQ4M2RlOWNlNGUiLCJUaW1lTXMiOjE2MzQyNTI1Mjk5MTN9", 
	"version":"0"
}
``` 
Where `value` is the JSON representation in base64 of binary field.

Is it possible to use `gprcurl` with this kind of binary field 

In case command were useful we are running it this way

```
grpcurl -vv \
    -insecure \
    -key /tmp/magma_protos/gateway.key \
    -cert /tmp/magma_protos/gateway.crt \
    -authority state-controller.magma.test \
    -protoset /tmp/magma_protos/out.protoset \
    -d '{"states": [{"type": "directory_record",
"deviceID": "IMSI001020000000064",
"value":"eyJTZXJpYWxpemVkUmVwb3J0ZWRTdGF0ZSI6ImV5SnBaR1Z1ZEdsbWFXVnljeUk2SUhzaWMyZDNYMk5mZEdWcFpDSTZJQ0l4TWpBeU5Ea3lOelk0SW4wc0lDSnNiMk5oZEdsdmJsOW9hWE4wYjNKNUlqb2dXeUpsT0RobFpUaGpZeTFoWVRoaUxUUXhPRGt0T0dZeE5DMDBNV1E0TTJSbE9XTmxOR1VpWFN3Z0luQjVMMjlpYW1WamRDSTZJQ0p0WVdkdFlTNWthWEpsWTNSdmNubGtMbkp3WTE5elpYSjJhV05sY2k1RWFYSmxZM1J2Y25sU1pXTnZjbVFpZlE9PSIsIlZlcnNpb24iOjAsIlJlcG9ydGVySUQiOiJlODhlZThjYy1hYThiLTQxODktOGYxNC00MWQ4M2RlOWNlNGUiLCJUaW1lTXMiOjE2MzQyNTI1Mjk5MTN9", "version":"0"}]}' \
    localhost:7443 \
    magma.orc8r.StateService/ReportStates
```

With the attached `out.protoset.txt`
[out.protoset.zip](https://github.com/fullstorydev/grpcurl/files/7350611/out.protoset.zip)

**Comment by jhump** [comment]
Yes: grpcurl can only do JSON unmarshaling with the schema -- it _must_ know the schema in order to do _anything_ (including deciding to base64-decode data for `bytes` fields). And per the JSON spec for protobufs, the value will be base64-decoded first.

Did you try this and it not work? (This should be very easy to try and then report a bug if you have a problem.)

**Comment by uri200** [comment]
Found the issue: the base64 string was wrong. Once we used the right one we are able to see the proper content 

Thanks!!!
