### ISSUE TITLE
Using grpcurl to connect to a service behind CloudFlare: `Message: : HTTP status code 521; transport: missing content-type field`

### ISSUE THREAD

**Issue by imWildCat** [fullstorydev/grpcurl#271]
I'm testing the source code of this project:
<https://github.com/Qv2ray/gun>

```shell
$ grpcurl -proto ./pkg/proto/gun.proto  -vv my.domain.com:443 GunService/Tun

Resolved method descriptor:
rpc Tun ( stream .Hunk ) returns ( stream .Hunk );

Request metadata to send:
(empty)

Response trailers received:
(empty)
Sent 0 requests and received 0 responses
ERROR:
  Code: Unknown
  Message: : HTTP status code 521; transport: missing content-type field
```

What could be the reason?

**Comment by jhump** [comment]
I have no idea. The gRPC client in grpcurl definitely includes the content-type, which will be "application/grpc+proto". Is it possible that the request is transiting some proxy that could be losing headers? Or could there be something weird somewhere that is treating headers as case-sensitive and looking for a specific case-spelling (e.g. "Content-Type" vs "Content-type" vs "content-type")? I would try routing through a debugging proxy or maybe just have your server (if you can) dump the entire HTTP request to see what's going on and figure out where the request is getting mangled.

**Comment by imWildCat** [comment]
Sorry for the late response.

I found the reason eventually:

https://community.cloudflare.com/t/grpc-go-support-message-http-status-code-521-transport-missing-content-type-field/325770/4
