### ISSUE TITLE
Failed to dial target host "localhost:5001": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sharooksubana** [fullstorydev/grpcurl#301]
I am also facing same issue -insecure flag works fine but I wanted to verify the self-signed cert can anyone give the good example how to use the -cacert flag and from where I should get the certificate

**Comment by kczulko** [comment]
I think [this](https://github.com/fullstorydev/grpcurl/issues/320#issuecomment-1213085737) answers the question and the issue can be closed.

**Comment by mafeifan** [comment]
I facing same issue
