### ISSUE TITLE
Feature request: Output stream response online

### ISSUE THREAD

**Issue by murfel** [fullstorydev/grpcurl#329]
I have a GRPC service with a method that returns a stream of messages. In particular, this is an infinite stream (use case: messenger). When I call this method with grpcurl, it doesn't show any output, as it never reaches the end of stream. Is it possible to output messages online, once they are received, without waiting for the end of stream? Thank you!

**Comment by dragonsinth** [comment]
Oh that's interesting.... that seems totally reasonable.

**Comment by dragonsinth** [comment]
Hi @murfel I was able to get this to work out of the box using the `chatterbox` example server, found here: https://github.com/fullstorydev/go/tree/master/examples/chatterbox
```
~/github/go/src/github.com/fullstorydev/go/examples/chatterbox grpcurl -import-path . -proto chatterbox.proto -plaintext -d '{}' 127.0.0.1:9000 chatterbox.ChatterBox/Monitor
{
  
}
{
  "who": "User 1",
  "what": "JOIN"
}
{
  "who": "User 1",
  "what": "CHAT",
  "text": "hi"
}
```

**Comment by murfel** [comment]
Hi @dragonsinth! Oh, thank you. I checked it myself and it does work. It was an error in my code. I must have been very tired debugging other stuff back then. Sorry for disruption!

**Comment by dragonsinth** [comment]
No worries, thanks for getting back and confirming! :)
