### ISSUE TITLE
Connecting to gRPC Service hosted on Azure App Service

### ISSUE THREAD

**Issue by sharooksubana** [fullstorydev/grpcurl#344]
I am trying to connect to the gRPC service which is hosted as Azure App Service using grpcurl, It gives below error 
Failed to dial target host "hostname:8585": context deadline exceeded.
Where As If I try the same in postman or if I create a console application by following steps as mentioned in below documentation [https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio#create-the-greeter-client](url) it works as expected. Anyone please let me know how to connect to the gRPC service hosted in Azure using grpcurl

**Comment by jhump** [comment]
If you are having the same issue from other tools, like postman, then that suggests this is not a grpcurl issue. It could be a number of things, most of them likely related to the network and the way your are trying to expose Azure resources to the internet. I think you should be looking into that: how to connect to your Azure app services from an external network.

**Comment by sharooksubana** [comment]
> 

In postman its working, I am facing issue only in grpcurl tool

**Comment by sharooksubana** [comment]
I found out why I was getting the **context deadline exceeded.** error, Because I was connecting to the wrong port though I have configured the gRPC Server to 8585 port the azure app service was exposed to 443 port so I have to connect to hostname:443
