### ISSUE TITLE
TestBrokenTLS_ClientHasExpiredCert fail with golang-1.21

### ISSUE THREAD

**Issue by mikelolasagasti** [fullstorydev/grpcurl#405]
Building grpcurl 1.8.7 with golang-1.21 for Fedora Rawhide fails in the following test:

~~~
--- FAIL: TestBrokenTLS_ClientHasExpiredCert (0.01s)
    tls_settings_test.go:217: expecting TLS certificate error, got: remote error: tls: expired certificate
~~~

**Comment by MyUmmaGumma** [comment]
Similar error on Manjaro Linux, grpcurl 1.8.7-1 - installing via makepkg
Is the fix to call `ClientTransportCredentials(...,..., "internal/testing/tls/wrong-client.crt",...)` instead of calling it with `internal/testing/tls/expired.crt` in tls_settings_test.go?

**Comment by dragonsinth** [comment]
https://github.com/fullstorydev/grpcurl/pull/408
