### ISSUE TITLE
insecure option not respected ?

### ISSUE THREAD

**Issue by mohanraj-r** [fullstorydev/grpcurl#41]
I am getting a TLS handshake error even when I specify the `-insecure` option 
Can you please help me understand what is going on

```
$ grpcurl -v -insecure localhost:9000 list
Failed to dial target host "localhost:9000": tls: first record does not look like a TLS handshake
```

main:
```go
func main() {
	lis, err := net.Listen("tcp", "localhost:9000")
	if err != nil {
		log.Fatal(err)
	}
	srv := grpc.NewServer()
	foo.RegisterFooServer(srv, &foo.Server{})
	srv.Serve(lis)
}
```

**Comment by jhump** [comment]
You want the `-plaintext` option. The `-insecure` option allows TLS even if the connection is considered insecure,  e.g. server does not have valid/trusted certificate.

**Comment by mohanraj-r** [comment]
Thanks, that works
