### ISSUE TITLE
Security Vulnerability: Update grpc version to at least 1.58.3

### ISSUE THREAD

**Issue by RohanNagar** [fullstorydev/grpcurl#431]
Recently a CVE was discovered which affects the current version of grpc used by this tool.

https://github.com/advisories/GHSA-m425-mq94-257g

Please update `google.golang.org/grpc` to `1.58.3` or higher.

**Comment by dragonsinth** [comment]
But grpcurl doesn't act as an http server?  So how are we actually vulnerable?

**Comment by RohanNagar** [comment]
Agreed that the vulnerability shouldn't actually affect grpcurl. Unfortunately, security scanners are flagging this for us so we are looking to have the package upgraded.

**Comment by enakshipriya** [comment]
+1

**Comment by cheslz** [comment]
+1 . Please :)

**Comment by dragonsinth** [comment]
This was already fixed here: https://github.com/fullstorydev/grpcurl/pull/427

**Comment by RohanNagar** [comment]
@dragonsinth any idea when the next release will be?

**Comment by dragonsinth** [comment]
IDK, I guess we could do one soon.  I figure anyone who super-cares can build from code using the latest Go, to also pull in any hypothetical Golang fixes.
