### ISSUE TITLE
BUG - Failed to list methods for service "tamama.grpc.Tamama": Symbol not found: tamama.grpc.Tamama

### ISSUE THREAD

**Issue by tamama** [fullstorydev/grpcurl#433]
Hi there,

There seems to be an issue with grpcul / grpcui listing methods...

gRPC server+reflection is written in C++ (gRPC version = 1.59.2; grpcrul = 1.8.9)

Listing service is OK
```
$ grpcurl -plaintext 127.0.0.1:31201 list
grpc.reflection.v1alpha.ServerReflection
tamama.grpc.Tamama
```

but listing methods is NOT OK:
```
$ grpcurl -plaintext 127.0.0.1:31201 list tamama.grpc.Tamama
Failed to list methods for service "tamama.grpc.Tamama": Symbol not found: tamama.grpc.Tamama
```

**Comment by tamama** [comment]
@jhump FYI

**Comment by tamama** [comment]
I answer my own question.

Quick fix: The bug is resolved after I combine all the types into one gigantic proto file.

:)

**Comment by jhump** [comment]
@tamama, it is not necessary to combine everything into one file. Most likely, something else was amiss before your refactor. The most common issue that causes issues with server reflection is using incorrect import paths. The path that you use to _compile_ a file must be the same path that other files use to _import_ it. A mismatch will cause runtime issues with reflection. You can read more about this [here](https://buf.build/docs/reference/protobuf-files-and-packages#imports).

**Comment by tamama** [comment]
Thanks!
