### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by leighmcculloch** [fullstorydev/grpcurl#47]
Hi! I love using grpcurl but installing it on new machines on first use can be pretty slow to download the dependencies and compile. Would it be possible to start releasing binaries?

Suggested approach I've used on my projects is to use `goreleaser` to build binaries for a few operating systems and architectures, then it will upload them to the releases page of this project. 

Is this something that could be added?

Thanks!

**Comment by leighmcculloch** [comment]
Example of what this looks like:

https://github.com/leighmcculloch/githubcloneall/releases
https://github.com/leighmcculloch/githubcloneall/blob/master/.goreleaser.yml
https://github.com/leighmcculloch/githubcloneall/blob/master/Makefile

**Comment by leighmcculloch** [comment]
It's great that the app is getting modules, it should make it more reliable and builds more reproducible which is great. It doesn't make it easier though, as all of the same dependencies still need to be pulled down. The process of pulling down and installing still takes longer than pulling down a binary that's already prebuilt.

I'd be happy to open a PR with a `goreleaser` setup that will build the binary for Linux, Mac, Windows, package it and put it into the GitHub releases. Let me know if you'd be up for a PR like that.

**Comment by jhump** [comment]
@leighmcculloch, sure `goreleaser` sounds interesting. Thanks!

**Comment by leighmcculloch** [comment]
On it!

**Comment by leighmcculloch** [comment]
@jhump See #49.
