### ISSUE TITLE
unknown import path "github.com/jhump/protoreflect/dynamic/grpcdynamic": cannot find module providing package github.com/jhump/protoreflect/dynamic/grpcdynamic

### ISSUE THREAD

**Issue by giuscri** [fullstorydev/grpcurl#69]
As of d86529bb4f81964b9fb9396dadaf0dbdf72a1a01, I tried to setup the project to reproduce a bug, but when running `make install` it says
```
$ make install
go install -ldflags '-X "main.version=dev build v1.0.0-15-gd86529b-dirty"' ./...
go: finding github.com/jhump/protoreflect/dynamic/grpcdynamic latest
go: finding github.com/jhump/protoreflect/grpcreflect latest
go: finding github.com/jhump/protoreflect/internal latest
go: finding github.com/jhump/protoreflect/dynamic latest
invoke.go:15:2: unknown import path "github.com/jhump/protoreflect/dynamic/grpcdynamic": cannot find module providing package github.com/jhump/protoreflect/dynamic/grpcdynamic
desc_source.go:14:2: unknown import path "github.com/jhump/protoreflect/grpcreflect": cannot find module providing package github.com/jhump/protoreflect/grpcreflect
../../go/pkg/mod/github.com/jhump/protoreflect@v1.1.0/desc/descriptor.go:18:2: unknown import path "github.com/jhump/protoreflect/internal": cannot find module providing package github.com/jhump/protoreflect/internal
make: *** [Makefile:21: install] Error 1
```

**Comment by jhump** [comment]
@giuscri, I can't reproduce. Sorry.

It looks like something is awry in your Go environment. The second line (I think?) indicates that it found the dependency it complains about below. And, if you look at the [source for v1.1.0](https://github.com/jhump/protoreflect/tree/v1.1.0/internal) of the protoreflect repo, you'll see the `internal` package that it says it can't find in that last error message.

CI for this repo does build without `GOPATH` using Go 1.11, which should mirror your setup I think. And it's green.

Maybe you could try nuking that `../../go/pkg` directory and trying again? Or see if you can get more verbose/debug output to see if that helps understand where the `go` tool is going afoul?

**Comment by giuscri** [comment]
not using Go much lately, I ended up removing my `~/go` and run `make deps`. Now it works!
