### ISSUE TITLE
`-d nested-json-string` error getting request data

### ISSUE THREAD

**Issue by Harold2017** [fullstorydev/grpcurl#88]
Thanks for this great tool!
when i try to send nested json data as a string by grpcurl, it throws out the following error:
`error getting request data: bad input: expecting string ; instead got {`

my data schema:
```json
{
  "origin": "test.jpg",
  "annotations": [
    {
      "title": "",
      "description": "",
      "view": {
        "y": 200,
        "x": 200
      }
    }
  ],
  "findings": [
    "finding_1",
    "finding_2",
    "finding_3"
  ],
  "image": "test_test.jpg"
}
```

sine the json data is too long for typing.. i use a make file to read in and pass it to grpcurl  as the following:
```bash
FILE := test.json
json := $(shell cat ${FILE})
data := '{"appid": "test_app", "jsonData": ${json}, "others": ""}'

grpcurl_test:
	grpcurl -insecure -d ${data} \
	localhost:10000 Service/method
```

Could you please give me some hints about this?
Thanks.

**Comment by jhump** [comment]
@Harold2017, looks to me like you are using the tool correctly.

That error message means that, while trying to unmarshal the JSON data into a request, it encountered the start of an object -- the curly brance `{` --  where it was expecting a string value. It expects string values as keys in an object (i.e. field names) and also for fields whose type in the protobuf source is `string` or `bytes`.

I can't help you troubleshoot further without a small repro case that includes the protobuf source for the service and message and a JSON payload that triggers the error.

**Comment by Harold2017** [comment]
@jhump , many thanks!
If i want to accept this request json as string on server side like the following .proto presents:
```
// reception
message Command {
    string appid = 1;  // sender tag
    string jsonData = 2;  // json string
    string others = 3;
}
```
do i need to change the reception type to `struct jsonData = 2` ?

I will try it later and update to you, thanks!

**Comment by jhump** [comment]
@Harold2017, yes, you'd need to import `"google/protobuf/struct.proto"` and then define the field's type as `google.protobuf.Struct`. That allows it to represent any JSON object.

As is, defined as a `string`, you'd need to nest that field's JSON payload into a string. Like so:

```json
{
  "appid": "foo",
  "jsonData": "{ \"nested\": \"json\" }",
  "others": "bar"
}
```

**Comment by Harold2017** [comment]
@jhump You're right! Many thanks!
