### ISSUE TITLE
Call service behind reverse proxy

### ISSUE THREAD

**Issue by Krever** [fullstorydev/grpcurl#89]
I'm trying to deploy my grpc service behind traefik proxy, so localhost:9999 becomes localhost:80/api. Sadly I cannot do anything with `grpcurl` because it complains when adress contains path as well. Is it wrong to run grpc in such a way?

```
╭─krever@wp-xps ~                                             
╰─$ grpcurl localhost/api list 
Failed to dial target host "localhost/api": dial tcp: address localhost/api: missing port in address 
╭─krever@wp-xps ~                                                
╰─$ grpcurl localhost:80/api list                                           
Failed to dial target host "localhost:80/api": dial tcp: address tcp/80/api: unknown port 
```

**Comment by jhump** [comment]
@Krever, how will your non-grpcurl clients connect? I think trying to use a path prefix is not standard gRPC and probably unsupported in gRPC client implementations (not just grpcurl's).

I think you need to either (A) use hostname-based routing with traefik for your gRPC services, not path-based routing, or (B) use something like grpc-gateway to add a REST facade in front of the gRPC service. If you go with A, you should be able to use the `-authority` option to set a hostname even if using `localhost` in the address.

**Comment by Krever** [comment]
Thank you, sorry for bothering ;)
