### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by brandonros** [fullstorydev/grpcurl#90]
How can I make this tool accept self-signed certs?

**Comment by brandonros** [comment]
`-insecure`

**Comment by gugahoi** [comment]
This is actually ignoring the handshake instead of accepting certificates. I assume the `cacert` option the the correct way about this but unsure?

**Comment by jhump** [comment]
@gugahoi, correct. If you want to verify the self-signed cert (vs. just trusting any server cert), you would add it to your set of trusted root certs with the `-cacert` option.

**Comment by mrdulin** [comment]
same issue for self-signed certificates generated by below shell script:
```sh
#!/bin/sh

echo "generating credentials and private key for server and client..."
openssl genrsa -out ./assets/server.key 2048

openssl req -new -x509 -days 3650 \
  -subj "/C=GB/L=China/O=grpo-server/CN=localhost" \
  -key ./assets/server.key -out ./assets/server.crt

openssl genrsa -out ./assets/client.key 2048

openssl req -new -x509 -days 3650 \
  -subj "/C=GB/L=China/O=grpo-client/CN=localhost" \
  -key ./assets/client.key -out ./assets/client.crt
```

**Comment by jhump** [comment]
@mrdulin, did you read the above comments and why the issue is closed? This is expected behavior. You have to configure grpcurl to either not check the cert (`-insecure`) or to trust it (`-cacert`).

**Comment by mrdulin** [comment]
@jhump I tried `-insecure` flags. 

```bash
☁  grpc-go-cnode [master] grpcurl localhost:3000 list -insecure
Failed to dial target host "localhost:3000": x509: certificate signed by unknown authority
```

server logs:
```bash
2020/08/28 12:32:41 http: TLS handshake error from [::1]:57648: remote error: tls: bad certificate
```

**Comment by mrdulin** [comment]
@jhump Thanks for reply. I tried `-insecure` flags, but still got same error.
```bash
☁  grpc-go-cnode [master] grpcurl localhost:3000 list -insecure                  
Failed to dial target host "localhost:3000": x509: certificate signed by unknown authority
```
server logs:
```bash
2020/08/28 12:38:50 http: TLS handshake error from [::1]:57784: remote error: tls: bad certificate
```

So, I want to try `-cacert` flag. How should I use this flag? Which certificate should be used?

**Comment by sharooksubana** [comment]
I am also facing same issue -insecure works fine but I wanted to verify the self-signed cert can anyone give the good example how to use the -cacert flag and from where should I get the certificate

**Comment by sharooksubana** [comment]
hi, Can anyone tell me how to use -cacert and which certificate to submit its been 2 months since I have stuck with it

**Comment by cavator** [comment]
i grpcurl -cacert=ca.pem -d='{"id":""}' user-service:443 GetUser
 still getting
 x509: certificate signed by unknown authority
any help?
