### ISSUE TITLE
Who broke the build?

### ISSUE THREAD

**Issue by xt0fer** [fullstorydev/grpcurl#91]
as of this date (and go version go1.12.1 darwin/amd64)

`$ go get github.com/fullstorydev/grpcurl`
results in
```
# github.com/fullstorydev/grpcurl
../GitHub/go/src/github.com/fullstorydev/grpcurl/grpcurl.go:600:4: undefined: grpc.WithContextDialer
```

**Comment by jhump** [comment]
The build is not broken.

The issue in Travis-CI that began last night is that `staticcheck` no longer supports Go 1.10 (and CI was configured to run the checks with that version of Go). In fact, if you look at the actual builds, you'll see that it's passing for 1.12.

Your version of the grpc-go repo is out-of-date. You can take a look at `go.mod` to see what version you need to upgrade to. Also, if you are using Go 1.12, then it will work if you enable Go modules:

```
GO111MODULE=on go get github.com/fullstorydev/grpcurl
```

**Comment by xt0fer** [comment]
roger. wilco. sorry
