### ISSUE TITLE
Enum with index 0 cannot be returned

### ISSUE THREAD

**Issue by vlgsiutin** [fullstorydev/grpcurl#95]
grpcurl version: 1.1.0
proto3 is used 

Case:
enum Status {
    ACTIVE = 0;
    INACTIVE = 1;
}

if Status is INACTIVE, return: 
{
  "status": "INACTIVE"
}

if Status is ACTIVE, return: {}
which should return 
{
  "status": "ACTIVE"
}

**Comment by jhump** [comment]
This is behaving as intended. Per the protobuf [spec for the JSON format](https://developers.google.com/protocol-buffers/docs/proto3#json):

> If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space.

You can change this behavior by providing the `-emit-defaults` flag, in which case default values will be explicitly included in the output (including for enum values).
