### ISSUE TITLE
Keep-alive - half the expected rate

### ISSUE THREAD

**Issue by vassilvk** [fullstorydev/grpcurl#99]
When using the `-keepalive-time` option, `grpcurl` sends keepalive pings to the server at half the expected rate.

Steps to reproduce
------------------
* Set up a gRPC service which listens, for example, on endpoint 1.2.3.4:123
* Run grpcurl with a 60 seconds keepalive-time ping against an API which takes say 5 min to complete:
```
./grpcurl -keepalive-time 60 1.2.3.4:123 my.Service/ExtremelySlowAPI
```
* Run `tcpdump` to monitor packets being sent from `grpcurl` to the service:
```
tcpdump -i eth0 dst 1.2.3.4
```

Expected
--------
You should see keepalive ping packets sent on the wire every 60 seconds.

Observed
--------
`tcpdump` reports 2 keepalive ping packets sent at once, every 120 seconds.

**Comment by jhump** [comment]
This should be fixed as of v1.5.0 (as part of updating grpc-go dependency in #136).
